name: Deploy Jaspr App

on:
  push:
    branches:
      - master  # Replace 'main' with your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: "Checkout Repository"
      uses: actions/checkout@v3

    # Step 2: Setup Dart environment
    - name: "Setup Dart"
      uses: dart-lang/setup-dart@v1.3

    # Step 3: Install Jaspr CLI and build the project
    - name: "Build Jaspr"
      run: |
        dart pub global activate jaspr_cli
        jaspr build --verbose

    # Step 4: Upload the build artifact for deployment
    - name: "Upload artifact"
      uses: actions/upload-artifact@v3
      with:
        name: jaspr-build
        path: 'build/jaspr'  # Path to the Jaspr build output

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Check out the repository
    - name: "Checkout Repository"
      uses: actions/checkout@v3

    # Step 2: Download the built artifact
    - name: "Download artifact"
      uses: actions/download-artifact@v3
      with:
        name: jaspr-build

    # Step 3: Deploy to GitHub Pages
    - name: "Setup Pages"
      uses: actions/configure-pages@v3

    - name: "Deploy to GitHub Pages"
      uses: actions/deploy-pages@v1
